### ISSUE TITLE
Using old `hop-cli` version on AWS platform prebuild script

### ISSUE THREAD

**Issue by lucassousaf** [gethop-dev/hop-cli#15]
We use a very old version of `hop-cli` in the [`02-install-hop-cli.sh`](https://github.com/gethop-dev/hop-cli/blob/main/resources/bootstrap/profiles/aws/.platform/hooks/prebuild/02-install-hop-cli.sh#L5) script. We should update it to use the latest version. I'm thinking that we probably should use a different strategy to keep things like this updated with the CLI. Because we'll have to remember to change it every single time we release a new version of the CLI.

**Comment by iarenaza** [comment]
I wonder if we could use a strategy similar to what we do with our own Docker images' tag names. Set a placeholder version (with some "special marker"), and then replace it with the latest available released version (for non tagged commits), or the tagged version for which we are running the build.

**Comment by iarenaza** [comment]
Fixed in commit ca1b5bbe. Closing now.
