### ISSUE TITLE
Develop bootstrapping tool

### ISSUE THREAD

**Issue by joseAyudarte91** [gethop-dev/hop-cli#2]
We need to develop main bootstrapping tool that will generate project files depending on the user settings.

The bootstrap tool will also handle infrastructure creation, using AWS Cloudformation templates and so on.

UPDATE-> Pending development

- [x] Make sure other missing or incomplete profiles are added to Settings.edn:
  - [x] CI
  - [x] Monitoring
- [x] Generate SQL code to be printed to the user for DB schema generation:
  - A set of schemas that will put different profile-related info.
- [x] Add example login page to Frontend profile. EDIT: we won't do a login page example in the authentication+frontend profiles because it's not useful for us as we always replace it when we start working on the project. If we want it for demo purposes we can create a demo profile later on.
- [x] `depends_on` docker compose dependencies.
- [x] We have a problem with HikariCP `config.edn` configuration. The underlying library  exposing the key `:duct.database.sql/hikari-cp` expects the key `:jdbc-url` but we are not providing it. We don't because we want to use the individual database environment variables instead of `JDBC_DATABASE_URL` for better compatibility with other services. The original HikariCP can work with the individual DB information pieces[1] as well as the Clojure wrapper for it. However, the Duct implementation for initializing the HikariCP library is making an [assumption](https://github.com/duct-framework/database.sql.hikaricp/blob/master/src/duct/database/sql/hikaricp.clj#L44) about the `:jdbc-url` or `:connection-uri` (can be provided via the `duct/module.sql`).
- [x] Make app ec2 instance type configurable in AWS Cloudformation's config through `settings.edn`.
- [x] Make memory distribution for different docker containers configurable. For that, we need to [obtain memory info](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-attribute.html) about selected ec2 instance type for the App and use it to show it to the user and/or manage memory limits programatically.
- [x] Adjust keycloak service to use user-configured memory settings assigned to the container's image. [We need to override `JAVA_OPTS`](https://github.com/keycloak/keycloak/blob/main/quarkus/dist/src/main/content/bin/kc.sh#L87-L91) in order to use container's specified memory settings as we do in other projects.
- [x] Finish implementing Keycloak profile (we need to include FE library).
- [x] Test the bootrstrap tool with a project using Github CI (whole cycle).
- [x] Have a strategy for deploy to prod env.
- [x] Add new config field in `settings.edn` for entering master branch name for CI, for the project and use it in the bootstrap.

[1] - with individual DB information pieces I mean this:
```clj
:server-name (tagged-literal 'duct/env ["APP_DB_HOST" 'Str])
:port-number (tagged-literal 'duct/env ["APP_DB_PORT" 'Str])
:database-name (tagged-literal 'duct/env ["APP_DB_NAME" 'Str])
:username (tagged-literal 'duct/env ["APP_DB_USER" 'Str])
:password (tagged-literal 'duct/env ["APP_DB_PASSWORD" 'Str])
:schema (tagged-literal 'duct/env ["APP_DB_SCHEMA" 'Str])
```

**Comment by lucassousaf** [comment]
The core features of the bootstrapping tool are done and further iterations should be addressed on new issues.
