### ISSUE TITLE
Add `on-premises` project support in the bootstrapping tool

### ISSUE THREAD

**Issue by joseAyudarte91** [gethop-dev/hop-cli#4]
The idea is to automate with a new "profile" configuration the less varied part of this kind of projects:

- Bundle generation script for generating docker container images and all the needed extra files so we can port the app in the most flexible way, without relying on an existing external docker registry.
- Provision with the needed scripts to start and stop application in dev and prod environments, assuming a specific set of tools are used: docker and docker-compose for instance.
- We should include the possibility of combining this profile with MQTT broker (a new profile would be needed as well; to be discussed).

Regarding the external configuration/infrastructure that can vary a lot, depending on each case, we will provide some tutorial with the specific set of tools we use in some existing projects and give additional links to use other tools as well.

Attached an example of SSL termination diagram, to see an overview of the parts to automate: all the elements behind the docker containers, separated by the dashed line.

![Image](https://user-images.githubusercontent.com/6231954/207114473-6c3da2d4-b77a-4fb0-ab75-2cf2b552f165.svg)

**Comment by lucassousaf** [comment]
Finished on commit 605d63b.
