### ISSUE TITLE
Implement a wizard (UI) for configuring the HOP CLI settings file

### ISSUE THREAD

**Issue by joseAyudarte91** [gethop-dev/hop-cli#9]
The goal is to develop a wizard (UI) that can be used by a user to generate/edit the Settings file used as configuration input for the HOP CLI.

For developing the UI, a web application format is desired, as it will make easier the development for us, as well as we keep control over the user experience, in comparison to other type of solutions.

In order to build the UI (frontend) part, we will use [Scittle](https://babashka.org/scittle/), in order to keep using Babashka for both the configuration and the launch processes of the HOP Applications, to make development easier and simpler, keeping everything in sync within the same repository.
Besides, Scittle supports plugins to integrate Reagent and Re-frame libraries, so we can work directly with CLJS and include JS if we want in the Frontend code, so it fits the needs.

Note: we need to include all the CLJS files we are going to use as part of the JS scripts loaded from the main `index.html` file, as that is like the classpath equivalent of the JVM side, regardless of the namespace requires we do in each CLJS namespace.

On the other hand, if we decide to integrate the Settings file configuration and launching as part of the same process, we might use some minimal Backend for this and we might use [this code](https://github.com/kloimhardt/babashka-scittle-guestbook) as example.

We are also going to provide a sidebar for navigating between the sections and choices: probably collapsed not to show all the nodes from the beginning, to make it more usable. Besides, it will be shown ony selected nodes as well, when showing choices-related nodes.

**UPDATE regarding missing tasks:**

- Improve general styling.
- Add collapse/expand feature to the sidebar and the main wizard's sections as well.
- Add validation to the wizard, so we make sure of:
  - Core profile cannot be unselected.
  - If we select some profiles we make sure that other profiles the former depends on are selected.
  - Other validations.

**Comment by lucassousaf** [comment]
The first iteration of the Wizard is done. Further changes should be addressed in new issues.
